# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: XCTest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-ios:
    runs-on: macos-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Install any dependencies
    - name: Install Dependencies
      run: swift package resolve

    # List available simulators (optional debug step)
    - name: List available iOS simulators
      run: xcrun simctl list devices

    # Run tests on iPhone 14 Simulator with iOS 16.0
    - name: Run Tests on iPhone 14 Simulator (iOS 16.0)
      run: |
        xcodebuild test \
          -scheme RequestifyTests \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0' \
          -sdk iphonesimulator \
          -configuration Debug \
          ONLY_ACTIVE_ARCH=NO
